### ISSUE TITLE
All options available in visual editor

### ISSUE THREAD

**Issue by aidbish** [Makin-Things/bom-radar-card#1]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
it would be nice if all the options are available in the visual editor for a card instead of having to go into the code editor for the card
This would make the card more appealing to newer HA users who may not yet be comfortable using the code editor

**Comment by DavidFW1960** [comment]
this would be cool..

**Comment by theOzzieRat** [comment]
This is something that I had already put in the todo section of the readme. Watch this space.
Considering it is such a nice thing for all card it appear to be difficult to find any good examples of how it is done. Most custom cards just expect you to use the text editor.

**Comment by aidbish** [comment]
Maybe we can reach out to the guys who do the front end stuff, they should be able to tell us. i think this should be standard IMO for all custom cards. 
Going to have a dig around some of the custom cards i use to see if they have something helpful for the booleans

in the built in entities card they have toggles for the "show hearder toggle" and "Colour icons based on state" wonder if the code for them would be useable?

**Comment by theOzzieRat** [comment]
The problem with the internal ones is they use a bunch of stuff that I don't think is available for custom cards to use.
Also 0.115 appears to have broken the old way of doing dropdown lists.

**Comment by theOzzieRat** [comment]
Unfortunately HA 0.115has broken the custom cards usage of the elements needed to do this. This will have to wait until that is resolved. See [https://github.com/home-assistant/frontend/issues/7098](https://github.com/home-assistant/frontend/issues/7098) for details.

**Comment by aidbish** [comment]
Just an update, i think they are reverting the change for lazy loading of card for the time being to give time to transition or alternatives
https://github.com/home-assistant/frontend/pull/7131
https://github.com/home-assistant/frontend/issues/7098

**Comment by theOzzieRat** [comment]
It has been reverted, but I am going to wait until they figure out a proper solution before spending time on something that may change again.

**Comment by LukePrior** [comment]
Do you have any updates on this was a proper solution found?

**Comment by theOzzieRat** [comment]
I just published a pre-release for this.  Please test and report any issues.
