### ISSUE TITLE
radar overlay images don't display

### ISSUE THREAD

**Issue by CanberraTinkerer** [Makin-Things/bom-radar-card#11]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
current
**Last working release (if known):**

**Browser and Operating System:**
Chrome on Windows 10

**Description of problem:**
no radar images appear on the map.  Looking at the HTTP requests made by the card, each call to https://api.weather.bom.gov.au/ results in a 404 error.  I've tried both of the examples given (national radar, and radar centred on Maryborough) as well as my local area (Canberra) without success.  I see the base map, but no radar overlays.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by DeanoAus** [comment]
Having the same issue here.

**Comment by theOzzieRat** [comment]
The BoM have changed the schema used for serving up the radar tiles.
v1.3.3 should fix it. Please update.

**Comment by DeanoAus** [comment]
Hah, I wrote that and then noticed you pushed a new one. Thanks for being responsive none the less :)

**Comment by theOzzieRat** [comment]
All good, was a little challenging to get the new url's since the BoM broke their own radar viewer. I had to install an android emulator to extract the new location (and then take a random guess).

**Comment by CanberraTinkerer** [comment]
Thanks!
