### ISSUE TITLE
Cannot update from v1.3.1 to v1.3.3 (Same as #12 and #13)

### ISSUE THREAD

**Issue by DaveOzzie** [Makin-Things/bom-radar-card#14]
**Checklist:**

- [ ] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by DaveOzzie** [comment]
**Last working release (if known):1.3.1

**Browser and Operating System:Chrome latest Win 10

Trying to update bom-radar through HACS> Its saying current ver 1.3.1 new ver 1.3.3 when pressed update HACS asks for refresh. upon refreshits back to ver 1.3.3 available
Tried reinstall through HACS. No changes..

Issues #12 & #13 were closed because they found a work around. I cannot figure out how to workaround the problem and I think the developer should be given the chance to repair the problem.

**Comment by Makin-Things** [comment]
You need to remove the old custom repository (use the three dots up the top right of HACS page) and add the new one.
https://github.com/makin-things/bom-radar-card

**Comment by DaveOzzie** [comment]
Ahhh, I had totally forgotten that this was a custom repository,
However when I try to delete the custom repository I get the message:
Could not use repository with ID 410705942 ('NoneType' object has no attribute 'data')

**Comment by Makin-Things** [comment]
HACS sometimes gets its knickers in a knot. Try restarting HA and then remove the old repo.

**Comment by DaveOzzie** [comment]
Thank you, that fixed it. Everyting is fine now.
