### ISSUE TITLE
Unable to update - possible cache issue?

### ISSUE THREAD

**Issue by austwhite** [Makin-Things/bom-radar-card#15]
**Checklist:**

- [ x] I updated to the latest version available (attempted and failed
- [ x] I cleared the cache of my browser

**Release with the issue:**
latest version (1.3.3)
**Last working release (if known):**
1.3.2b
**Browser and Operating System:**
Windows 10 Edge and Chrome, Windows 11 Edge

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Makin-Things** [comment]
On the 25 Sep 2021 the repository was relocated to a new GitHub account with the release of v1.3.4. If you currently have it installed using HACS you will need to go into HACS and remove the old custom repository (the three dots up the top right) and add the new repository and then update the card. The link below has been updated to the new location. Your existing configs will not be lost.

https://github.com/Makin-Things/bom-radar-card

**Comment by austwhite** [comment]
I did actually re-add the repository using the new one in HACS and it still tried to install from the old one.  I don't know if that is a HACS issue or what.   
Is there a cache in HACS that may need to be cleared?   I am not brilliant with the programming side, but if there is a cache file or something I can certainly find it and delete it

**Comment by Makin-Things** [comment]
HACS sometimes seems a bit stupid. Try restarting HA and then try the reinstall.

**Comment by austwhite** [comment]
I'll uninstall, restart HA then reinstall and see if it triggers it to look in the right place.

**Comment by austwhite** [comment]
That seems to have worked.  Removed the repository, rebooted and then readded the updated repository.

Thanks for your help.  I appreciate it.   

I'll close this issue now
