### ISSUE TITLE
Not turning up in HACS either as integration or front end

### ISSUE THREAD

**Issue by Bazmundi** [Makin-Things/bom-radar-card#16]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Didn't read manual, first time using custom repositories.

**Comment by Makin-Things** [comment]
You need to follow the install instructions and add the custom repository.

https://github.com/Makin-Things/bom-radar-card#install
