### ISSUE TITLE
local radar loop does not display 2022.4

### ISSUE THREAD

**Issue by RXM307** [Makin-Things/bom-radar-card#18]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:1.6.0

**Last working release (if known): Unknown new install

**Browser and Operating System: Chrome, Windows 10 (IOS also homeassistant App)

**Description of problem: local radar overlay radar loop does not display, Australia wide radar loop is working**

**Javascript errors shown in the web inspector (if applicable):**
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
0422c555.js:1 Uncaught (in promise) https://<XXXX>:8123/config/www/community/bom-radar-card/bom-radar-card.js
```

**Comment by RXM307** [comment]
same issue with master also

**Comment by Makin-Things** [comment]
I am using 2022.4.5 and can't reproduce the problem with v1.6.0. Did you install using HACS or manually? Also please post the text version of the card config (remove a few of the less significant digits of lat/lon values to avoid posting your home address).

**Comment by RXM307** [comment]
Thank You, I see the problem there was a quote at the bottom in the zoom_level (Copied from the example) have removed that and it's working correctly now...

type: custom:bom-radar-card
frame_count: 10
center_latitude: XX
center_longitude: XX
marker_latitude: XX
marker_longitude: XX
show_marker: true
show_range: true
show_zoom: true
show_recenter: true
show_playback: true
zoom_level: 8'
