### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by DavidFW1960** [Makin-Things/bom-radar-card#2]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
1.2.10
**Last working release (if known):**
unknown
**Browser and Operating System:**
chrome/win10

**Description of problem:**
Console error

**Javascript errors shown in the web inspector (if applicable):**

![image](https://user-images.githubusercontent.com/36390762/97644094-7a5c7780-1a9d-11eb-9543-683f2171d320.png)
```

```

**Additional information:**

**Comment by theOzzieRat** [comment]
This isn't actually an error, just chrome looking for something extra when dev tools are activated. Warning removed in 1.2.11 anyway.
