### ISSUE TITLE
Show Single Latest Image with Auto-Refresh Period

### ISSUE THREAD

**Issue by warwickbuilds** [Makin-Things/bom-radar-card#20]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- Check Box to only show a single radar image - being the latest image available
- Refresh this single image with the latest from the source at a set/customisable period. Depending on source and publishing schedules of that source

**Additional context**
I have a control panel dashboard in my house, I would like to show a radar image on a section of this. Currently the radar is rotating 5 or so images which is janky and distracting on a otherwise static control panel.
I would like to show a static image of the latest radar image and then a button of click action through to the currently available rotating radar images.

**Comment by Makin-Things** [comment]
This should be possible by setting the frame count to 1.
Closing as there will be a completely rewritten version soon (hopefully) using the latest unpublished BoM api's.
