### ISSUE TITLE
BoM radar images not visible at zoom level 10

### ISSUE THREAD

**Issue by addinsella** [Makin-Things/bom-radar-card#24]
**Checklist:**

- [y ] I updated to the latest version available
- [y ] I cleared the cache of my browser
- [y ] I installed using HACS (leave unchecked for manual installs)

**Release with the issue: 2.0.6**

**Last working release (if known): unknown**

**Browser and Operating System: Chrome (Windows)**

**Card Config:**
```
type: custom:bom-radar-card
data_source: BoM
center_latitude: -33.7
center_longitude: 151.2
zoom_level: 10
marker_latitude: -33.7
marker_longitude: 151.2
show_marker: true
show_zoom: true
square_map: true
show_recenter: false
extra_labels: false
show_range: false
show_scale: false
show_radar_location: false
show_radar_coverage: false
show_playback: true
```

**Description of problem: BoM radar is not visible at zoom level 10.**

The card does not show the BoM radar images when zoomed all the way in (i.e. zoom level 10)

**Comment by mcclown** [comment]
I'm seeing this as well but only on Android devices. It works fine for me on Windows. I've tested on a Samsung S20+ and an 8" Samsung Galaxy Tab A

**Comment by Makin-Things** [comment]
No longer relevant due to changes from the BoM. Please create a new issue if the problem persists in V3 (it will be a while as it is a total rewrite).
