### ISSUE TITLE
Support auto light/dark theme colour

### ISSUE THREAD

**Issue by Nick-Adams-AU** [Makin-Things/bom-radar-card#25]
**Is your feature request related to a problem? Please describe.**
I use a theme that automatically changes from light to dark when the sun sets and then reverse when the sun comes up. The bom-radar-card is either hard coded to light or dark which looks out of place against the opposite theme colour.

**Describe the solution you'd like**
Support automatically matching the system theme colour.

**Comment by Makin-Things** [comment]
There current version of the card is going to be replaced (time permitting) using the newer BoM api's. They don't even provide a dark version so this is not going to be possible.
