### ISSUE TITLE
Ability to resize card

### ISSUE THREAD

**Issue by oneseventhree** [Makin-Things/bom-radar-card#26]
**Is your feature request related to a problem? Please describe.**
Is it possible to resize the card? - It's too tall and too large for what I need to show on my dashboard

**Describe the solution you'd like**
Adjust by pixel would be great

**Comment by ghost** [comment]
Another vote for this from me too, would be great if we could specify a size.;

I'm using it in a horizontal stack card, which is nested in a vertical stack card, using panel mode.  Intended use is a dashboard running on a tv screen in my lunch room.

**Comment by Makin-Things** [comment]
Closing as the card is getting a complete rewrite. Please reopen or create a new issue if the problem still persists once v3 is released (it will be a while).
