### ISSUE TITLE
Weather tiles are not correct

### ISSUE THREAD

**Issue by legaultjm** [Makin-Things/bom-radar-card#28]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser
- [X ] I installed using HACS (leave unchecked for manual installs)

**Release with the issue:**
2.1.1

**Last working release (if known):**
unknown

**Browser and Operating System:**
Seems to happen everywhere, all OS, all browsers

**Card Config (click Show Code Editor and copy paste your config, remove a few of the least significant digits of your lat/lon to avoid posting you exact home address):**

type: custom:weather-radar-card
card_title: Radar
data_source: RainViewer-TITAN
map_style: Dark
zoom_level: 10
center_latitude: 30.4
center_longitude: -97.7
extra_labels: true
square_map: false
show_range: false
show_playback: false
show_zoom: false
show_marker: true
show_scale: false
static_map: false
marker_latitude: 30.4
marker_longitude: -97.7
frame_count: 24
frame_delay: 100

**Description of problem:**

The radar does not seem to have anything to do with where I am. The map is correct, but weather radar is not aligned with the current or historic weather condition that I can correlate. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by Makin-Things** [comment]
This is a radar card for Australia, your coordinates are in the US so it is never going to work.
