### ISSUE TITLE
API Being retired?

### ISSUE THREAD

**Issue by simongis** [Makin-Things/bom-radar-card#29]
I see the [BOM page](https://weather.bom.gov.au/onboarding) now has a banner: **"This page will be retired on 14 March 2023"**

I believe the API used for the map tiles will also be retired.  Have you heard of any alternative APIs they will be providing?

**Comment by bossanova808** [comment]
Argh that is...not good.

Does not per se say the whole API.  

Might be good if weather interested people start gathering resources and info here....

**Comment by simongis** [comment]
If I find an alternative source, will post here.

**Comment by Line-Noise** [comment]
Can confirm. It's pissing down in Melbourne right now and the radar on my Home Assistant display is clear. :disappointed:

**Comment by bossanova808** [comment]
The API (i.e. for data) is still working, at least.  As is the old FTP based radar (so my Kodi addon is fine still).

But the pages are gone...and I guess the new tile radar too then :(

**Comment by Makin-Things** [comment]
The api for the weather forecasts and observations are not affected, but the radar tiles have been update/moved to a new location.
Unfortunately I have not had any spare time (and won't until at least late June) to figure out where they have been moved.
Because it is all encrypted and now there is only a mobile app that uses it means having to do a MTIM attack on an android or apple device to get the new urls. Painful and time consuming to set up. If someone else wants to help by figuring out the new schema it is then probably a fairly easy update.
In the meantime you can still choose any of the rainviewer options and get the data from there.

**Comment by Line-Noise** [comment]
I have a rooted Android phone and I need to spin up `mitmproxy` to get my PowerPal API key so I'll open the radar on the BoM app at the same time and see what I can find.

**Comment by kiwizznz** [comment]
Ah, wondered where all the clouds had gone. If only.. (Melbourne weather joke etc etc)

**Comment by kiwizznz** [comment]
> I have a rooted Android phone and I need to spin up `mitmproxy` to get my PowerPal API key so I'll open the radar on the BoM app at the same time and see what I can find.

Can't you just get the API key for PowerPal from the app? I signed up for their pro device beta thing at it shows up there - maybe they could just give you your key if you ask?

**Comment by Makin-Things** [comment]
@Line-Noise if you can do the mitm stuff that would be awesome.  Basically I am looking for the new schema for the tiles. Before they removed them the urls looked like this.

```https://radar-tiles.service.bom.gov.au/tiles/{time}/{z}/{x}/{y}.png```

Where the various bits in {} specify exactly the tile you want. I doubt that much has changed, probably the main part of the url and possibly the order of the parameters.

**Comment by Line-Noise** [comment]
> Can't you just get the API key for PowerPal from the app? I signed up for their pro device beta thing at it shows up there - maybe they could just give you your key if you ask?

Yeah, apparently if you were part of the beta you can. But I'm not so can't. No worries. I've got it now!

**Comment by Line-Noise** [comment]
It looks like BoM are using mapbox.com now. The URLs are in the form of:

`https://api.mapbox.com/v4/bom-dc-prod.rain-prod-LPR-{time}/{z}/{x}/{y}.vector.pbf`

. . . plus an API access token appended which I won't post here. It returns a protobuf. I assume you'd need to use the Mapbox SDK to extract the tile data out of the protobuf file. However I can change `vector.pbf` to `vector.png` and I get an image back so a URL swap might be possible! (Although I just tried and all I'm getting back are black tiles. :disappointed: Maybe the x, y, z coordinates have changed?)

I'm happy to privately send you the mitm dump if you want to look at it yourself.

**Comment by kaizersoje** [comment]
> 

Same here for today in Melbourne as well.

**Comment by kaizersoje** [comment]
> Can confirm. It's pissing down in Melbourne right now and the radar on my Home Assistant display is clear. 😞

Same here for today in Melbourne as well.

**Comment by DavidFW1960** [comment]
> > Can confirm. It's pissing down in Melbourne right now and the radar on my Home Assistant display is clear. 😞
> 
> Same here for today in Melbourne as well.

switch to using rainviewer option as the source

**Comment by roly151** [comment]
Is the rainviewer rain radar data accurate? I tried their app and it shows vastly different radar pictures if you choose one radar over another.

**Comment by DavidFW1960** [comment]
> Is the rainviewer rain radar data accurate? I tried their app and it shows vastly different radar pictures if you choose one radar over another.

It seems accurate to me. It was pissing down here yesterday and the eye of the storm on the radar was right overhead.

**Comment by roly151** [comment]
Never mind me. I think it may have been one of the radars on the RainViewer app not working. You can click a radar location and one of them (Sydney) had no rain over Sydney, whereas the other (Woollongong) had a large amount of rain.

**Comment by Makin-Things** [comment]
I managed to decode the new api calls. The bad news is that they have completely changed how they deliver radar tiles (now encoded vectors instead of png tiles). This means that to get it working again with BOM data will require a total rewrite of the card, which unfortunately will not happen any time soon.
It still works with rainviewer data.

**Comment by Makin-Things** [comment]
I made some progress over the weekend and have figured out how to extract the data using javascript.
![image](https://user-images.githubusercontent.com/91187456/227802861-4ba53f31-5793-48fa-b56a-4ecb5cde0f32.png)
So a new radar card is possible, but it will take time that I am short of atm.

**Comment by Makin-Things** [comment]
Closing in favour of #32 

Please follow the progress on the new version of the card and if you are a dev I could use some help. Especially if you have experience with typescript (I find it to be a battle as I normally do backend stuff).
