### ISSUE TITLE
Error: Custom element doesn't exist: bom-radar-card

### ISSUE THREAD

**Issue by Tovrin** [Makin-Things/bom-radar-card#3]
I've just installed the card and am getting the following:

**Custom element doesn't exist: bom-radar-card.**

**type: 'custom:bom-radar-card'
frame_count: 10
center_latitude: xxxxx (proper co-ords are here)
center_longitude: xxxxx
marker_latitude: xxxxx
marker_longitude: xxxxx
show_marker: true
show_range: true
show_zoom: true
show_recenter: true
show_playback: true
zoom_level: 4**

My configuration.yaml includes the following:

**lovelace:
  mode: yaml
  resources:
    - url: /local/bom-radar-card/bom-radar-card.js
      type: module**

**frontend:
  javascript_version: auto**

The file structure is:

**config
|-- www
|---- bom-radar-card
|------ bom-radar-card.js
|------ home-circle-dark.svg
|------ home-circle-light.svg
|------ leaflet.css
|------ leaflet.js
|------ leaflet.toolbar.min.css
|------ leaflet.toolbar.min.js
|------ pause.png
|------ play.png
|------ radar-colour-bar.png
|------ recenter.png
|------ skip-back.png
|------ skip-next.png**

I'm not sure I know what I'm doing wrong.  Please help.

**Comment by Tovrin** [comment]
Hi again.  The "Error: Custom element doesn't exist: bom-radar-card" came good overnight (go figure), but I'm just getting a blank map with a white bar at the bottom.

What have I done wrong?

**Comment by theOzzieRat** [comment]
There is a problem with the card finding the resources it needs when not installed using HACS (ie. different paths to things). I will try and fix over the next few days, but in the meantime I would suggest using HACS to install it. That also gives you the added bonus of having easy upgrades when they happen.

**Comment by Tovrin** [comment]
I would have used HACS but I can't seem to find it there.

**Comment by theOzzieRat** [comment]
You just need to add https://github.com/theOzzieRat/bom-radar-card as a custom repository. Click the 3 dots up the top right afer going into HACS.

**Comment by Tovrin** [comment]
Awesome.  Thanks!  Works perfectly now :)

**Comment by EvanJ85** [comment]
> You just need to add https://github.com/theOzzieRat/bom-radar-card as a custom repository. Click the 3 dots up the top right afer going into HACS.

Can I suggest you add this explicit instruction to the Install section, for others who are noobs like me?
Thank you for this amazing card.

**Comment by theOzzieRat** [comment]
README updated in 1.2.12.
