### ISSUE TITLE
When used on a panel view this card keeps on expanding vertically.

### ISSUE THREAD

**Issue by mcclown** [Makin-Things/bom-radar-card#31]
Thanks for creating this, it was just what I needed. I've come across this issue though.

**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser
- [x ] I installed using HACS (leave unchecked for manual installs)

**Release with the issue:**
v2.1.0

**Last working release (if known):**

**Browser and Operating System:**
Windows 11 / Chrome 110.0.5481.96

**Card Config (click Show Code Editor and copy paste your config, remove a few of the least significant digits of your lat/lon to avoid posting you exact home address):**

```
type: custom:bom-radar-card
data_source: RainViewer-Original
show_marker: true
show_radar_coverage: false
extra_labels: false
show_range: false
map_style: Voyager
zoom_level: 10
center_latitude: -33.90
marker_latitude: -33.90
center_longitude: 151.15
marker_longitude: 151.15
static_map: false
show_scale: false
show_radar_location: false
show_playback: false
show_zoom: false
square_map: false
show_recenter: true
restart_delay: 5000
frame_delay: 1000
```

When I configure this on a view type of Panel (ie. it is the only card on its own view on my dashboard) it keeps on slowly expanding vertically, flickering each time it expands its height. I've tried differed data-sources, just in case there was one tile reporting the wrong size but it seems to happen for all of them.

**Comment by Makin-Things** [comment]
I am not going to attempt to fix this on the current version of the card as the BoM have made some massive changes to the delivery of radar data.
I have started completely rewriting the card, so this is most likely going to go away with the new version.
