### ISSUE TITLE
Repostitory structure for v1.2.11 is not HACS compliant

### ISSUE THREAD

**Issue by troykelly** [Makin-Things/bom-radar-card#4]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
V1.2.11

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
Unable to add custom repository to HACS

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by DavidFW1960** [comment]
This repo gets added as lovelace or front end... not an integration

**Comment by theOzzieRat** [comment]
As David mentioned, you are adding it the wrong way. README updated in 1.2.12.
