### ISSUE TITLE
No releases have compiled bom-radar-card.js asset

### ISSUE THREAD

**Issue by huonw** [Makin-Things/bom-radar-card#5]
**Checklist:**

N/A

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:** every release (including V1.2.14)

**Last working release (if known):** none

**Browser and Operating System:** N/A

**Description of problem:**

The readme describes a manual installation process:

> If you don't use HACS, you can download js file from [latest releases](https://github.com/theOzzieRat/bom-radar-card/releases). ...

Unfortunately, it looks like the release CI is consistently failing (e.g. https://github.com/theOzzieRat/bom-radar-card/runs/1490808664?check_suite_focus=true ) and so the compiled asset isn't being attached.

I'm not an expert in the npm tooling, but one potential fix might be to use `npm ci` rather than `npm install`.

(Thanks for making and publishing this card!)

**Javascript errors shown in the web inspector (if applicable):**

N/A

**Additional information:**

**Comment by theOzzieRat** [comment]
The source code assets had all the needed files in the dist folder, but I have now fixed the pipelines. You need all of the assets not just bom-radar-card.js.
It has only been released as a pre-release (V1.2.15) to avoid the majority of people that use HACS getting a meaningless update.

**Comment by huonw** [comment]
Great, thanks! 🎉 

Minor detail, but the README says "download js file", and so it sounds like it could be adjusted to specify downloading a whole set of files? (Another option might be to zip up the `dist` folder so that there's just one release asset to download 🤷 )

**Comment by theOzzieRat** [comment]
I have updated the README to change it to be all files. I tried doing it as a zip, but that seems to break using HACS and I am not willing to do that. The doco update will just slip in with the next release whenever that is.
