### ISSUE TITLE
Release 1.2.15 bug

### ISSUE THREAD

**Issue by DavidFW1960** [Makin-Things/bom-radar-card#6]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
Just released version now gives red screen....
**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by theOzzieRat** [comment]
Yes trying to fix a pipeline issue, hence why it was marked pre-release. I can only test this by making a release unfortunately. Stay with 1.2.14, there are no real changes.

**Comment by theOzzieRat** [comment]
A working pre-release for V1.2.15 is now available. No actual code changes just updating CI pipelines to address issue #5. This version will not be released formally. It will just get included when 1.2.16 is needed.
