### ISSUE TITLE
Map tiles not loading

### ISSUE THREAD

**Issue by dcwilli** [Makin-Things/bom-radar-card#7]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**
Chrome and Windows 10
Chrome and Windows 10, tried on edge, with the same results

**Description of problem:**
The map is showing like a disjointed puzzle piece and I was wondering how to rectify it?
![image](https://user-images.githubusercontent.com/55827604/102032723-4fd43d00-3e05-11eb-8e2f-f310f95e6681.png)

**Javascript errors shown in the web inspector (if applicable):**
![image](https://user-images.githubusercontent.com/55827604/102033608-99be2280-3e07-11eb-94c0-da264573561d.png)

 BOM-WEATHER-CARD  Version 0.85c    
bom-radar-card.js:287   BOM-RADAR-CARD   Version 1.2.14    
leaflet.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
default_view:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://192.168.0.160:8123/static/fonts/roboto/Roboto-Bold.woff2

leaflet.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
chunk.e47a73c83c941745c8d4.js:160 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://192.168.0.160:8123/static/fonts/roboto/Roboto-Light.woff2

default_view:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://192.168.0.160:8123/static/fonts/roboto/Roboto-RegularItalic.woff2

2VM539 about:srcdoc:8 GET http://192.168.0.160:8123/local/community/bom-radar-card/leaflet.css net::ERR_ABORTED 404 (Not Found)

```

**Additional information:**

type: 'custom:bom-radar-card'
frame_count: 15
center_latitude: -27.544466653565152
center_longitude: 153.08784129084407
marker_latitude: -27.544466653565152
marker_longitude: 153.08784129084407
show_marker: true
show_range: true
show_zoom: true
show_recenter: true
show_playback: true
zoom_level: 10
frame_delay: 500
show_scale: true
map_style: satellite
static_map: true
show_radar_coverage: true
show_radar_location: true

![image](https://user-images.githubusercontent.com/55827604/102033504-5368c380-3e07-11eb-8290-c2d1955f45fb.png)

**Comment by theOzzieRat** [comment]
I have loaded your configuration and it is working perfectly. Did you use HACS or do a manual install?

**Comment by dcwilli** [comment]
> I have loaded your configuration and it is working perfectly. Did you use HACS or do a manual install?

Hello, I used HACS

**Comment by theOzzieRat** [comment]
Ok. Just check that your www/community/bom-radar-card has all of these files.
![image](https://user-images.githubusercontent.com/3675762/102039067-efe99080-3e1c-11eb-8ddd-67c67d82af32.png)

**Comment by dcwilli** [comment]
@theOzzieRat Looks like my leaflet.css is named "leaflet.css.css" I'll rename it, restart and check.

![image](https://user-images.githubusercontent.com/55827604/102042777-705cc100-3e1e-11eb-9bbc-4eaea631b235.png)

**Comment by dcwilli** [comment]
I've renamed the file, still not working though. Not sure what I'm doing wrong :(

**Comment by dcwilli** [comment]
OK awesome, working now! @theOzzieRat Thank you for your help!

**Comment by theOzzieRat** [comment]
Thanks for the update and glad you got it working. I have no idea why that happened. I actually uninstalled and the installed it again and I am not getting that happening.

**Comment by dcwilli** [comment]
@theOzzieRat Yeah I'm not sure why either, it might have something to do with HACS. Again, thanks for your help! Awesome Frontend Integration!
