### ISSUE TITLE
Tiles display

### ISSUE THREAD

**Issue by leogaggl** [Makin-Things/bom-radar-card#8]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
2021.01.5
**Last working release (if known):**
unknown (did not notice prior to V1)
**Browser and Operating System:**
OS:
- OS Ubuntu 20.04LTS
- ChromeOS Latest Stable
- Andoid

Browsers:
- Firefox Latest Stable
- Chrome Latest Stable

**Description of problem:**
I have noticed that the radar images in Zoom Level 9 that there seems to be a consistent display issue with missing tiles of the radar image over the OSM map layer.

I have attached a screenshot to visualise. When you zoom out there is no issue. Also zooming in to Zoom Level 10 it also works fine.

I have changed the default level to 8 (from the original config below) and the outcome is the same. All zoom levels other than 9 seem to work.

![radar](https://user-images.githubusercontent.com/199995/105677831-4a0d6380-5f3c-11eb-9a4e-99b3426a683e.png)

**Card config:**

```
type: 'custom:bom-radar-card'
frame_count: 10
center_latitude: -35.xxxxxxx
center_longitude: 138.xxxxxxx
marker_latitude: -35.xxxxxxx
marker_longitude: 138.xxxxxxx
show_marker: true
show_range: true
show_zoom: true
show_recenter: true
show_playback: true
zoom_level: 9
```

**Additional information:**

This is just a minor issue. Just thought I report if you can find a cause.

Thanks for the great work! One of the most useful HA cards for me!

**Comment by theOzzieRat** [comment]
I have seen this also. When I investigated it there where tiles missing on the bom server (ie. they failed to publish them). When this occurred for me it also affected the bom's mobile app as well as their new radar viewer at https://weather.bom.gov.au/
There is nothing I can do to fix them not publishing all the tiles. If you see it happen again please check if it occurs on the bom's apps. Maybe we can report a bug to them through the mobile app.
Closing for now.
