### ISSUE TITLE
Zoom Restrictions

### ISSUE THREAD

**Issue by kingy444** [Makin-Things/bom-radar-card#9]
It appears that the Zoom for Maps is currently restricted at '10'

I have tried to adjust further both in UI and YAML but it doesnt zoom any further.

Not sure if this is a restriction in code, as directly on OpenWeatherMaps website i can zoom further than this so hoping to have further zoom enabled (even if only via YAML)

**Comment by theOzzieRat** [comment]
Unfortunately this is not possible. It uses the radar tiles as published by the BOM and this is the limit of the zoom. Past this zoom level all the radar information vanishes on the map.
Have a look at weather.bom.gov.au and you will see the same limits on zoom.
